export const postsTypes = {
    GET_ALL_REQUEST : 'GET_ALL_REQUEST',
    GET_ALL_SUCCESS : 'GET_ALL_SUCCESS',
    GET_ALL_ERROR : 'GET_ALL_ERROR',
    
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS:'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_ERROR:'GET_CATEGORY_ERROR'
}